#
# use defaults (_00build.conf)
#
# but override these settings:

## Download and include custom SFS (XDRV_INC= overrides this)
#ADRV_SFS_URL=
#YDRV_SFS_URL=
FDRV_SFS_URL= https://download1527.mediafire.com/vafmxd811trgqmMFaoqpbgsN5n_0MW1v1dvEetSu_9SVo6t1wLp4elX-GOK-vlnBeqOJZ0xuRPGT2L-UcgxLSwLy0XQFRrGXI9LDX4AFjfYUxkMIgVEMN1pZsaS9I6ZqNacSJ-zePt5mx-FfGP2ISTcvSZeCS-M9OXOFoNHUU5g/ga93l6qzzkx83m4/linux_firmware_20250302.sfs
